import type { Database } from "@/types/database";
import type { User, Course, Lesson, Enrollment, Progress } from "@/types";
type DbUser = Database["public"]["Tables"]["users"]["Row"];
type DbCourse = Database["public"]["Tables"]["courses"]["Row"];
type DbLesson = Database["public"]["Tables"]["lessons"]["Row"];
type DbEnrollment = Database["public"]["Tables"]["enrollments"]["Row"];
type DbProgress = Database["public"]["Tables"]["progress"]["Row"];
export type UserRole = "admin" | "student";
export type CourseLevel = "beginner" | "intermediate" | "advanced";
export type EnrollmentStatus = "active" | "completed" | "dropped";
export type LessonType = "video" | "reading" | "quiz";
export declare function mapDbUserToApp(dbUser: DbUser): User;
export declare function mapDbCourseToApp(dbCourse: DbCourse): Course;
export declare function mapAppCourseToDb(course: Omit<Course, "id" | "createdAt" | "updatedAt">): Database["public"]["Tables"]["courses"]["Insert"];
export declare function mapDbLessonToApp(dbLesson: DbLesson): Lesson;
export declare function mapAppLessonToDb(lesson: Omit<Lesson, "id">): Database["public"]["Tables"]["lessons"]["Insert"];
export declare function mapDbEnrollmentToApp(dbEnrollment: DbEnrollment): Enrollment;
export declare function mapDbProgressToApp(dbProgress: DbProgress): Progress;
export {};
